### ISSUE TITLE
Unable to search by ssn last 4 in gcims due to ciw not inserting hashed ssn last 4 correctly

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CIW#145]

**Comment by tsaunders-gsa** [comment]
Code has been merged into Dev.

Pull Request: https://github.com/GSA/CIW/pull/146

**Comment by tsaunders-gsa** [comment]
Code was released on 3/30/2018

**Comment by jgoodell-gsa** [comment]
successfully tested and seems to work as expected
