### ISSUE TITLE
BCC All System E-Mails to Secondary E-mail Address

### ISSUE THREAD

**Issue by dlenz-gsa** [GSA/CIW#193]
For the purpose of archiving, all system-generated e-mails should BCC HSPD-12's archiving mailbox.

**Comment by dlenz-gsa** [comment]
Associated with the same task in the following repositories:
GCIMS: https://github.com/GSA/GCIMS/issues/414
12-Year: https://github.com/GSA/12YearEnrollment/issues/56
CHRIS: https://github.com/GSA/CHRISUpdate/issues/126

**Comment by tsaunders-gsa** [comment]
This has been done.
