### ISSUE TITLE
Remove GenerateEMailBody Function

### ISSUE THREAD

**Issue by tsaunders-gsa** [GSA/CIW#2]
GenerateEMailBody is not used within the application and therefore does not need to be in the code.

`GenerateEMailBody`

**Comment by jgoodell-gsa** [comment]
CIW\ProcessCIW\Utilities\Utilities.cs(48)  Removed. Had 0 references
CIW\ProcessCIW\Process\CIWEMails.cs(149) Same name 1 reference. not removed

**Comment by tsaunders-gsa** [comment]
This issue has been resolved.

**Comment by tsaunders-gsa** [comment]
This issue still needs to go through testing.
