### ISSUE TITLE
Process CIWs with Tier 2S Investigations as Tier 2

### ISSUE THREAD

**Issue by dlenz-gsa** [GSA/CIW#202]
When a CIW with an investigation type of "Tier 2S" is uploaded to GCIMS, it should be processed as a Tier 2 investigation.

**Comment by tsaunders-gsa** [comment]
I believe we just need to change the SP.  If Tier 2S is passed in then change it to Tier 2.

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: April 16, 2020
**Test Environment**: Test

**Comment by dlenz-gsa** [comment]
### TEST EXECUTION
**Tested By**: David Lenz
**Test Status**: Passed
**Test Date**: April 20, 2020
**Test Environment**: Production
