### ISSUE TITLE
Change README.md (Config Files)

### ISSUE THREAD

**Issue by tsaunders-gsa** [GSA/CIW#5]
We can simplify the setup process by just having the user copy AppSettings.example and ConnectionStrings.example to the output directory and rename to AppSettings.config and ConnectionStrings.example

**Comment by jgoodell-gsa** [comment]
Cloned the repo into a new local repo, copied the 2 config files into bin/debug folder. builds and runs in debug mode. The solution does have a reference to these 2 files when you clone the repo but the files are missing so you just have to delete the 2 broken references from visual studio solution explorer.

**Comment by tsaunders-gsa** [comment]
This issue has been resolved.
