### ISSUE TITLE
Send runtime errors to developers

### ISSUE THREAD

**Issue by tsaunders-gsa** [GSA/CIW#91]
We need a way to send runtime errors to developers if the application crashes.

**Comment by jgoodell-gsa** [comment]
* [Release script started for this issue](https://drive.google.com/open?id=18XxN_pbbWOJScrF1xlQapQ1tfZCY-9PVWrqmmjT9Sz0)

**Comment by jgoodell-gsa** [comment]
* Branch created for issue
* Coded solution to send emails and log errors for all un-handled exceptions caught inside the scope of main function

**Comment by tsaunders-gsa** [comment]
Code has been merged into Dev.

Pull Request: https://github.com/GSA/CIW/pull/133
