### ISSUE TITLE
Prior inv issue

### ISSUE THREAD

**Issue by jgoodell-gsa** [GSA/CIW#97]
Issue identified with CIW that allows spaces to be entered into prior investigation date.
* if no and date ask if they meant yes for prior
* if no and space just null out
* if no and there is a date say did you mean yes for prior investigation because you have a date
* if prior date is a space just null it out all the time

**Comment by tsaunders-gsa** [comment]
This has been merged into dev.

Pull Request: https://github.com/GSA/CIW/pull/98
